version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf:/etc/mysql/conf.d:ro
    networks:
      - camagru

  apache-php:
    image: apache-php
    depends_on:
      - mariadb
    container_name: apache-php
    build: ./back
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
      - "9003:9003"
    volumes:
      - ./back/src:/var/www/html
    networks:
      - camagru

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MYSQL_VOLUME}

networks:
  camagru:
